python3 user.py benshapiro
python3 user.py FoxNews
python3 user.py jordanbpeterson
python3 user.py newsmax
python3 user.py nytimes
python3 user.py Reuters
python3 user.py TheEconomist
python3 user.py TMZ
python3 user.py cnnbrk
python3 user.py CNN
python3 user.py BBCBreaking
python3 user.py washingtonpost
python3 user.py BarackObama
python3 user.py justinbieber
python3 user.py katyperry
python3 user.py rihanna
python3 user.py cristiano
python3 user.py taylorswift13
python3 user.py realDonaldTrump[2]
python3 user.py ArianaGrande[3]
python3 user.py ladygaga
python3 user.py elonmusk
python3 user.py TheEllenShow
python3 user.py narendramodi
python3 user.py YouTube
python3 user.py KimKardashian
python3 user.py selenagomez
python3 user.py jtimberlake
python3 user.py cnnbrk
python3 user.py Twitter[a]
python3 user.py BillGates
python3 user.py cnn
python3 user.py neymarjr
python3 user.py britneyspears
python3 user.py nasa
python3 user.py ddlovato
python3 user.py shakira
python3 user.py nytimes
python3 user.py jimmyfallon
python3 user.py kingjames
python3 user.py bbcbreaking
python3 user.py pmoindia
python3 user.py srbachchan
python3 user.py imvkohli
python3 user.py MileyCyrus
python3 user.py JLo
python3 user.py bts_twt
python3 user.py akshaykumar
python3 user.py beingsalmankhan
python3 user.py oprah
python3 user.py brunomars
python3 user.py iamsrk
python3 user.py niallofficial
python3 user.py realmadrid
python3 user.py fcbarcelona
python3 user.py championsleague
python3 user.py sportscenter
python3 user.py KylieJenner
python3 user.py espn
python3 user.py drake
python3 user.py bts_bighit
python3 user.py Harry_Styles
python3 user.py sachin_rt
python3 user.py kevinhart4real
